"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import type { PdfReportOptions } from "@/types/report";

export function createPdfDocument(title: string, orientation: "p" | "l" = "p") {
  const doc = new jsPDF({ orientation, unit: "mm", format: "a4" });
  doc.setProperties({ title });

  return doc;
}

export function formatCurrency(value: string | number | null | undefined) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(Number(value ?? 0));
}

export function formatDate(value?: string | Date | null) {
  if (!value) {
    return "-";
  }

  return new Intl.DateTimeFormat("id-ID", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

export function addPdfHeader(doc: jsPDF, options: PdfReportOptions) {
  const period = options.period?.fromDate || options.period?.toDate
    ? `${options.period?.fromDate ?? "awal"} - ${options.period?.toDate ?? "akhir"}`
    : "Semua periode";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Sistem Informasi Ekspedisi Online", 14, 15);
  doc.setFontSize(13);
  doc.text(options.title, 14, 23);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Periode: ${period}`, 14, 31);
  doc.text(`Dicetak oleh: ${options.generatedBy.name}`, 14, 37);
  doc.text(`Role: ${options.generatedBy.role}`, 14, 43);
  if (options.generatedBy.branchName) {
    doc.text(`Cabang: ${options.generatedBy.branchName}`, 14, 49);
  }
  doc.text(`Tanggal generate: ${formatDate(new Date())}`, 14, options.generatedBy.branchName ? 55 : 49);
}

export function addPdfSummary(doc: jsPDF, summary: Record<string, string | number>) {
  const rows = Object.entries(summary).map(([label, value]) => [label, String(value)]);

  autoTable(doc, {
    body: rows,
    startY: 62,
    theme: "grid",
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: "bold", fillColor: [240, 244, 242] },
    },
  });
}

export function addPdfTable(
  doc: jsPDF,
  columns: string[],
  rows: (string | number)[][],
  startY?: number,
) {
  const finalY = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY;

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: startY ?? (finalY ? finalY + 8 : 70),
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: [22, 41, 35], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [247, 249, 248] },
    margin: { left: 10, right: 10 },
    didDrawPage: () => addPdfFooter(doc),
  });
}

export function addPdfFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("Generated by Sistem Informasi Ekspedisi Online", 14, pageHeight - 8);
    doc.text(`Halaman ${page} dari ${pageCount}`, pageWidth - 42, pageHeight - 8);
  }
}

export function downloadPdf(doc: jsPDF, filename: string) {
  addPdfFooter(doc);
  doc.save(filename);
}
